update workflow

diff --git a/.github/workflows/infra-setup.yml b/.github/workflows/infra-setup.yml
--- a/.github/workflows/infra-setup.yml
+++ b/.github/workflows/infra-setup.yml
@@ -6,6 +6,11 @@ on:
       - main
     paths:
       - "infra-setup/**"
+  push:
+    branches:
+      - main
+    paths:
+      - "infra-setup/**"
   workflow_dispatch:
 
 env:
@@ -29,7 +34,7 @@ jobs:
         shell: bash
         working-directory: ./infra-setup
     outputs:
-        tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
+      tfplanExitCode: ${{ steps.tf_plan.outputs.exitcode }}
 
     steps:
       - uses: actions/checkout@v4
@@ -45,93 +50,59 @@ jobs:
             -backend-config="container_name=${TF_VAR_container_name}" \
             -backend-config="key=${TF_VAR_tfstate_key}"
 
-      - name: Terraform Format
-        id: Format
-        run: terraform fmt -check
-
       - name: Terraform Validate
         run: terraform validate
 
       - name: Terraform Plan
-        id: tf-plan
+        id: tf_plan
         run: |
-          export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-          if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-          else 
-          exit 0
+          set +e
+          terraform plan -detailed-exitcode -no-color -out tfplan
+          EXITCODE=$?
+          echo "exitcode=$EXITCODE" >> $GITHUB_OUTPUT
+          set -e
+          if [ $EXITCODE -eq 1 ]; then
+            echo "Terraform plan failed!"
+            exit 1
           fi
 
-      - name: Generate Plan --output
+      - name: Upload Terraform Plan
         uses: actions/upload-artifact@v4
         with:
-          name: plan
-          path: ./infra-setup/runplan.tfplan
-
-      - name: Create String Output
-        id: tf-plan-string
-        run: |
-          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-
-          delimiter="$(openssl rand -hex 8)"
-          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```terraform' >> $GITHUB_OUTPUT
-          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "${delimiter}" >> $GITHUB_OUTPUT
-
-      - name: Publish Terraform Plan to Task Summary
-        env:
-          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-        run: |
-          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-
-      - name: Push Terraform Output to PR
-        if: github.ref != 'refs/heads/main'
-        uses: actions/github-script@v7
-        env:
-          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const body = `${process.env.SUMMARY}`;
-            github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: body
-            })
+          name: tfplan
+          path: ./infra-setup/tfplan
 
   terraform-apply:
     name: "Terraform Apply"
-    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
+    needs: [plan]
+    if: github.ref == 'refs/heads/main' && needs.plan.outputs.tfplanExitCode == '2'
     runs-on: ubuntu-latest
     environment: production
-    needs: [terraform-plan]
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./infra-setup
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
+        uses: hashicorp/setup-terraform@v3.1.2
 
       - name: Terraform Init
-        run: terraform init
+        run: |
+          terraform init \
+            -backend-config="resource_group_name=${TF_VAR_rg_name}" \
+            -backend-config="storage_account_name=${TF_VAR_storage_name}" \
+            -backend-config="container_name=${TF_VAR_container_name}" \
+            -backend-config="key=${TF_VAR_tfstate_key}"
 
       - name: Download Terraform Plan
         uses: actions/download-artifact@v4
         with:
           name: tfplan
+          path: ./infra-setup
 
       - name: Terraform Apply
         run: terraform apply -auto-approve tfplan
